apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: petstore
  description: The Pet Store system is a full-stack application that provides information and services for various pets available for adoption.
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  lifecycle: experimental
  owner: team-petstore
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: petstore-frontend
spec:
  type: website
  system: petstore
  lifecycle: experimental
  owner: team-petstore
  consumesApis:
    - petstore-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: petstore-backend
spec:
  type: service
  system: petstore
  lifecycle: experimental
  owner: team-petstore
  providesApis:
    - petstore-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petstore-api
spec:
  type: openapi
  lifecycle: production
  owner: team-petstore
  system: petstore
  definition:
    $text: https://raw.githubusercontent.com/swagger-api/swagger-petstore/master/src/main/resources/openapi.yaml
