apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: docs-example
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: library
  owner: user:guest
  lifecycle: experimental
  system: examples
