site_name: oauth
nav:
  - Home: index.md
  - Diagrams: diagrams.md
  - Code: code.md
theme:
  name: material
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ''
plugins:
  - techdocs-core
