---
- hosts: all
  tasks:
    - name: Copy OCI image
      copy:
        src: ../backstage.tar
        dest: /tmp/backstage.tar

    - name: Import OCI image
      containers.podman.podman_load:
        input: /tmp/backstage.tar
      become: true
      register: backstage_image

    - name: Remove image file
      file:
        dest: /tmp/backstage.tar
        state: absent
    
    - name: Debug | Image metadata
      debug:
        msg: "{{ backstage_image }}"
        verbosity: 1

    - name: Gather facts for Backstage container
      containers.podman.podman_container_info:
        name: backstage
      become: true
      register: backstage_container

    - name: Debug | Print container state
      debug:
        msg: "{{ backstage_container }}"
        verbosity: 1

    - name: Stop old Backstage container
      containers.podman.podman_container:
        name: backstage
        state: stopped
      become: true
      when: "backstage_container.containers | length > 0"

    - name: Remove old Backstage container
      containers.podman.podman_container:
        name: backstage
        state: absent
      become: true
      when: "backstage_container.containers | length > 0"

    - name: Create configuration directory
      file:
        dest: /etc/backstage
        state: directory
      become: true

    - name: Deploy configuration
      template:
        dest: /etc/backstage/app-config.production.yaml
        src: ../app-config.production.yaml
        force: false
      become: true

    - name: Create new Backstage container
      containers.podman.podman_container:
        name: backstage
        state: present
        image: "{{ backstage_image.image.Id }}"
        pull: never
        ports:
          - "7007:7007/tcp"
        volume:
          - "/etc/backstage/app-config.production.yaml:/app/app-config.production.yaml:ro"
        restart_policy: "on-failure:5"
      become: true

    - name: Start Backstage
      containers.podman.podman_container:
        name: backstage
        state: started
      become: true
